#!/bin/sh
#ff3a228e-39fc-4c4e-9aa5-09e144da397a
usage() {
  echo "Usage: $(basename $0) --keys [key1 key2...] -- [arguments to gpg]"
}

keys=""

parsekeys() {
  for arg in $@; do
    case $arg in
      --)
        break
        ;;
      --*|-*)
        break
        ;;
      *)
        if [[ $keys == "" ]]; then
          keys="$arg"
        else
          keys="$keys $arg"
        fi
        shift
        ;;
    esac
  done
}

while [[ $1 != "--" ]] && [[ $# -gt 0 ]]; do
  case $1 in
    "--keys" | "--key")
      shift
      parsekeys $@
      ;;
    "--help")
      usage
      exit 0
      ;;
    --*|-*)
      echo "Unknown argument $1"
      exit 2
      ;;
    *)
      shift
      ;;
  esac
done

if [[ $1 == "--" ]]; then
  shift # Remove final --
else
  usage
  exit 2
fi

if [[ $keys == "" ]]; then
  usage
  exit 2
fi

keyring_dir="/run/user/$(id -u)/$$-keyring/"

rm -fr $keyring_dir # Just in case there's an old one laying around

mkdir -p $keyring_dir
chmod -R 700 $keyring_dir # Only the user running this should have access

cleanup() {
  rm -fr $keyring_dir
}
trap cleanup EXIT

for key in $keys; do
  command gpg --pinentry-mode loopback --quiet --homedir $keyring_dir --import $key
done

extraargs="--output -"
for arg in $@; do
  if [[ $arg == "-o" ]] || [[ $arg == "--output" ]]; then
    extraargs=""
    break
  fi
done

command gpg --always-trust --pinentry-mode loopback $extraargs --homedir $keyring_dir $@
